"""
AILog ChatGPT Importer

Converts ChatGPT's official export format (conversations.json) into AILogFile.

ChatGPT export format:
  - User exports via Settings → Data Controls → Export data
  - Downloads a zip file containing conversations.json
  - conversations.json is an array of conversation objects
  - Each conversation has a `mapping` field (dict of node_id -> node)
  - Each node has: id, message (with author.role, content.parts, create_time, model), parent, children
  - The message tree is rooted at a node with no parent
  - `current_node` points to the latest node in the active branch

Supported ChatGPT content types:
  - Text messages (content.parts is a list of strings)
  - Code artifacts (content.content_type == 'code')
  - DALL-E images (content.content_type == 'image_asset_pointer')
  - System messages
  - Tool calls (browsing, code execution)
"""

from __future__ import annotations

import json
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from ailog.core.models import (
    AILogFile,
    AILogFileMetadata,
    Interaction,
    Message,
    Artifact,
    SensitivityInfo,
    RiskLevel,
    Role,
    ContentType,
    ArtifactType,
    OwnerInfo,
    OwnerIdType,
)
from ailog.importers.base import BaseImporter


def _ts_to_iso(ts: Optional[float]) -> str:
    """Convert Unix timestamp (float) to ISO 8601 string."""
    if ts is None:
        return ""
    try:
        dt = datetime.fromtimestamp(ts, tz=timezone.utc)
        return dt.isoformat().replace("+00:00", "Z")
    except (ValueError, OSError, OverflowError):
        return ""


def _extract_text(content: Any) -> str:
    """
    Extract text from ChatGPT's content field.
    
    ChatGPT content formats:
      - Simple: {"parts": ["Hello"]}  →  "Hello"
      - Multi-part: {"parts": ["text1", {"type": "code", ...}]}  →  concatenated
      - String: "Hello"  →  "Hello"
    """
    if isinstance(content, str):
        return content
    if isinstance(content, dict):
        parts = content.get("parts", [])
        if not parts:
            return ""
        texts = []
        for part in parts:
            if isinstance(part, str):
                texts.append(part)
            elif isinstance(part, dict):
                # Could be a code block or other structured content
                if "text" in part:
                    texts.append(part["text"])
                elif "content" in part:
                    texts.append(str(part["content"]))
        return "\n".join(texts)
    return str(content) if content else ""


def _map_role(chatgpt_role: str) -> Role:
    """Map ChatGPT author role to AILog Role."""
    mapping = {
        "user": Role.USER,
        "assistant": Role.ASSISTANT,
        "system": Role.SYSTEM,
        "tool": Role.TOOL,
    }
    return mapping.get(chatgpt_role, Role.USER)


def _detect_content_type(text: str, chatgpt_content: Any) -> ContentType:
    """Detect content type from text and ChatGPT content metadata."""
    if isinstance(chatgpt_content, dict):
        ct = chatgpt_content.get("content_type", "")
        if ct == "code":
            return ContentType.CODE
        if ct == "image_asset_pointer":
            return ContentType.IMAGE
        if ct == "execution_output":
            return ContentType.CODE
    # Heuristic: if text starts with ``` it's likely markdown with code
    if text.strip().startswith("```"):
        return ContentType.MARKDOWN
    if "```" in text:
        return ContentType.MARKDOWN
    return ContentType.TEXT


def _extract_artifacts(
    content: Any, message_idx: int
) -> List[Artifact]:
    """
    Extract artifacts from ChatGPT message content.
    
    Artifacts include:
      - Code blocks generated by ChatGPT Code Interpreter
      - DALL-E generated images
    """
    artifacts = []
    if not isinstance(content, dict):
        return artifacts

    # Code Interpreter artifacts
    if content.get("content_type") == "code":
        language = content.get("language", "python")
        code_text = _extract_text(content)
        artifacts.append(
            Artifact(
                id=f"art_ci_{message_idx}",
                type=ArtifactType.CODE,
                name=f"code_interpreter_{message_idx}.{_lang_to_ext(language)}",
                content=code_text,
                language=language,
                source_message_index=message_idx,
            )
        )

    # DALL-E image artifacts
    if content.get("content_type") == "image_asset_pointer":
        asset_pointer = content.get("asset_pointer", "")
        artifacts.append(
            Artifact(
                id=f"art_dalle_{message_idx}",
                type=ArtifactType.IMAGE,
                name=f"dalle_image_{message_idx}.png",
                url=asset_pointer,
                source_message_index=message_idx,
            )
        )

    # Multi-part content may contain embedded code blocks
    parts = content.get("parts", [])
    for part_idx, part in enumerate(parts):
        if isinstance(part, dict) and part.get("type") == "code":
            lang = part.get("language", "")
            code = part.get("text", "")
            if code:
                artifacts.append(
                    Artifact(
                        id=f"art_emb_{message_idx}_{part_idx}",
                        type=ArtifactType.CODE,
                        name=f"embedded_code_{message_idx}_{part_idx}.{_lang_to_ext(lang)}",
                        content=code,
                        language=lang or None,
                        source_message_index=message_idx,
                    )
                )

    return artifacts


def _lang_to_ext(language: str) -> str:
    """Convert programming language name to file extension."""
    mapping = {
        "python": "py",
        "javascript": "js",
        "typescript": "ts",
        "java": "java",
        "c": "c",
        "cpp": "cpp",
        "csharp": "cs",
        "go": "go",
        "rust": "rs",
        "ruby": "rb",
        "php": "php",
        "swift": "swift",
        "kotlin": "kt",
        "sql": "sql",
        "html": "html",
        "css": "css",
        "shell": "sh",
        "bash": "sh",
        "r": "r",
    }
    return mapping.get(language.lower(), "txt")


def _walk_message_tree(
    mapping: Dict[str, Any],
    current_node: str,
) -> List[Dict[str, Any]]:
    """
    Walk the ChatGPT message tree from root to current_node,
    following the active branch at each fork.
    
    ChatGPT's mapping is a tree structure. The main conversation path
    is determined by following each node's children down to current_node.
    For nodes with multiple children, we pick the one that leads to current_node.
    
    Returns a flat list of message nodes in conversation order.
    """
    if not mapping:
        return []

    # Find root (node with no parent)
    root_id = None
    for node_id, node in mapping.items():
        if node.get("parent") is None:
            root_id = node_id
            break

    if root_id is None:
        return []

    # Build path from current_node back to root
    path_set = set()
    node_id = current_node
    while node_id:
        path_set.add(node_id)
        node = mapping.get(node_id)
        if not node:
            break
        node_id = node.get("parent")

    # Walk from root forward, only following nodes in the path
    ordered = []
    node_id = root_id
    while node_id:
        node = mapping.get(node_id)
        if not node:
            break
        if node_id in path_set:
            ordered.append(node)
        # Find next child in the path
        children = node.get("children", [])
        next_id = None
        for child_id in children:
            if child_id in path_set:
                next_id = child_id
                break
        if not children or next_id is None:
            break
        node_id = next_id

    return ordered


def _parse_conversation(
    conv: Dict[str, Any], conv_idx: int
) -> List[Interaction]:
    """
    Parse a single ChatGPT conversation into AILog Interactions.
    
    A ChatGPT conversation contains multiple turns. Each turn
    typically has a user message followed by an assistant message.
    We group consecutive user+assistant pairs into Interactions.
    """
    mapping = conv.get("mapping", {})
    current_node = conv.get("current_node", "")
    conv_title = conv.get("title", "Untitled")
    conv_id = conv.get("id", f"conv_{conv_idx}")
    create_time = conv.get("create_time")

    # Walk the message tree
    nodes = _walk_message_tree(mapping, current_node)

    # Group into interactions (user+assistant pairs)
    interactions = []
    pending_user_msg = None
    pending_user_idx = None
    turn_index = 0
    all_artifacts = []

    for msg_idx, node in enumerate(nodes):
        message = node.get("message")
        if not message:
            continue

        author = message.get("author", {})
        role_str = author.get("role", "")
        if role_str not in ("user", "assistant", "system", "tool"):
            continue

        role = _map_role(role_str)
        content = message.get("content", {})
        text = _extract_text(content)
        if not text.strip() and not content:
            continue

        content_type = _detect_content_type(text, content)
        msg_model = message.get("model", "")
        create_ts = message.get("create_time")

        # Extract artifacts
        artifacts = _extract_artifacts(content, msg_idx)
        all_artifacts.extend(artifacts)

        msg = Message(
            role=role,
            content=text,
            content_type=content_type,
            timestamp=_ts_to_iso(create_ts),
            model=msg_model or None,
            model_provider="openai" if msg_model else None,
            custom={
                "chatgpt_message_id": message.get("id", ""),
                "chatgpt_conversation_id": conv_id,
                "chatgpt_title": conv_title,
            },
        )

        if role == Role.USER:
            pending_user_msg = msg
            pending_user_idx = msg_idx
        elif role == Role.ASSISTANT:
            turn_index += 1
            messages = []
            artifacts_for_turn = []
            if pending_user_msg:
                messages.append(pending_user_msg)
            messages.append(msg)

            # Assign artifacts from this turn
            for art in all_artifacts:
                if (
                    pending_user_idx is not None
                    and art.source_message_index is not None
                    and pending_user_idx <= art.source_message_index <= msg_idx
                ):
                    artifacts_for_turn.append(art)
            all_artifacts = [
                a for a in all_artifacts if a not in artifacts_for_turn
            ]

            # Determine interaction timestamp from first message
            ts = messages[0].timestamp if messages[0].timestamp else _ts_to_iso(create_time)

            interaction = Interaction(
                id=f"ix_{conv_id}_{turn_index}",
                timestamp=ts,
                session_id=f"sess_{conv_id}",
                turn_index=turn_index,
                messages=messages,
                artifacts=artifacts_for_turn,
                sensitivity=SensitivityInfo(
                    max_risk_level=RiskLevel.LOW,
                    detected_items=[],
                    scanned_by="none",
                ),
                custom={
                    "chatgpt_title": conv_title,
                },
            )
            interactions.append(interaction)
            pending_user_msg = None
            pending_user_idx = None

    # Handle orphan user message (no assistant reply)
    if pending_user_msg:
        turn_index += 1
        interactions.append(
            Interaction(
                id=f"ix_{conv_id}_{turn_index}",
                timestamp=pending_user_msg.timestamp or _ts_to_iso(create_time),
                session_id=f"sess_{conv_id}",
                turn_index=turn_index,
                messages=[pending_user_msg],
                sensitivity=SensitivityInfo(
                    max_risk_level=RiskLevel.LOW,
                    detected_items=[],
                    scanned_by="none",
                ),
                custom={"chatgpt_title": conv_title},
            )
        )

    return interactions


def _load_conversations(source_path: Path) -> List[Dict[str, Any]]:
    """
    Load conversations from source path.
    
    Supports:
      - conversations.json directly
      - ChatGPT export zip file (extracts conversations.json)
      - Directory containing conversations.json
    """
    source = source_path.resolve()

    # Case 1: Direct JSON file
    if source.is_file() and source.suffix == ".json":
        with open(source, "r", encoding="utf-8") as f:
            data = json.load(f)
        if isinstance(data, list):
            return data
        elif isinstance(data, dict) and "mapping" in data:
            # Single conversation object (not wrapped in array)
            return [data]
        else:
            raise ValueError(f"Unexpected JSON structure in {source}")

    # Case 2: Zip file
    if source.is_file() and source.suffix == ".zip":
        with zipfile.ZipFile(source, "r") as zf:
            # Find conversations.json in the zip
            candidates = [
                n for n in zf.namelist() if n.endswith("conversations.json")
            ]
            if not candidates:
                raise ValueError(f"No conversations.json found in {source}")
            with zf.open(candidates[0]) as f:
                data = json.load(f)
            if isinstance(data, list):
                return data
            return [data]

    # Case 3: Directory
    if source.is_dir():
        conv_file = source / "conversations.json"
        if conv_file.exists():
            return _load_conversations(conv_file)
        # Check for zip files
        zip_files = list(source.glob("*.zip"))
        if zip_files:
            return _load_conversations(zip_files[0])
        raise ValueError(f"No conversations.json or zip found in {source}")

    raise ValueError(f"Cannot load conversations from {source}")


class ChatGPTImporter(BaseImporter):
    """Import ChatGPT conversations into AILog format."""

    platform_id = "chatgpt"
    platform_url = "https://chat.openai.com"

    def detect(self, source_path: str | Path) -> bool:
        """Detect if source is a ChatGPT export."""
        source = Path(source_path).resolve()

        if source.is_file():
            if source.suffix == ".zip":
                try:
                    with zipfile.ZipFile(source, "r") as zf:
                        return any(
                            n.endswith("conversations.json")
                            for n in zf.namelist()
                        )
                except zipfile.BadZipFile:
                    return False
            if source.suffix == ".json":
                try:
                    with open(source, "r", encoding="utf-8") as f:
                        data = json.load(f)
                    if isinstance(data, list) and len(data) > 0:
                        first = data[0]
                        return isinstance(first, dict) and "mapping" in first
                    if isinstance(data, dict) and "mapping" in data:
                        return True
                except (json.JSONDecodeError, UnicodeDecodeError):
                    return False

        if source.is_dir():
            return (source / "conversations.json").exists() or bool(
                list(source.glob("*.zip"))
            )

        return False

    def parse(self, source_path: str | Path) -> AILogFile:
        """Parse ChatGPT export into ALogFile."""
        conversations = _load_conversations(Path(source_path))

        all_interactions = []
        for conv_idx, conv in enumerate(conversations):
            interactions = _parse_conversation(conv, conv_idx)
            all_interactions.extend(interactions)

        # Sort by timestamp
        all_interactions.sort(key=lambda ix: ix.timestamp or "")

        # Re-index turn_index globally per session
        session_turns: Dict[str, int] = {}
        for ix in all_interactions:
            if ix.session_id not in session_turns:
                session_turns[ix.session_id] = 0
            session_turns[ix.session_id] += 1
            ix.turn_index = session_turns[ix.session_id]

        metadata = self._build_metadata(
            tags=["chatgpt-export"],
            custom={
                "source_conversations_count": len(conversations),
                "source_interactions_count": len(all_interactions),
            },
        )

        return AILogFile(
            ailog_version="0.1",
            metadata=metadata,
            interactions=all_interactions,
        )